CREATE TABLE IF NOT EXISTS RESULT(

    ID INT AUTO_INCREMENT PRIMARY KEY,
    LOCAL_TEAM VARCHAR(50),
    VISITING_TEAM VARCHAR(50),
    GOL_LOCAL_TEAM INT,
    GOL_VISITING_TEAM INT
);

CREATE TABLE IF NOT EXISTS TOURNEY (

    NAME_TOURNEY VARCHAR(50) PRIMARY KEY,
    YEAR_TOURNEY INT PRIMARY KEY

);

CREATE TABLE IF NOT EXISTS USER_PRODE (

    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME_USER VARCHAR(50),
    NAME_TOURNEY VARCHAR(50),
    YEAR_TOURNEY INT,

    CONSTRAINT FOREIGN KEY FK_USER_TOURNEY(NAME_TOURNEY, YEAR_TOURNEY) REFERENCES TOURNEY(NAME_TOURNEY, YEAR_TOURNEY),
);

CREATE TABLE IF NOT EXISTS FECHA_TOURNEY(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    FECHA INT,
    NAME_TOURNEY VARCHAR(50),
    YEAR_TOURNEY INT,
    ID_RESULT INT,
    CONSTRAINT FOREIGN KEY FK_FECHA_TOURNEY_TOURNEY(NAME_TOURNEY, YEAR_TOURNEY) REFERENCES TOURNEY(NAME_TOURNEY, YEAR_TOURNEY),
    CONSTRAINT FOREIGN KEY FK_FECHA_TOURNEY_RESULT(ID_RESULT) REFERENCES RESULT(ID)
);

CREATE TABLE IF NOT EXISTS SCORE(

     ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
     SUM_PARTIAL_FECHA INT,
     SUM_TOTAL_FECHA INT,
     SUM_PARTIAL_TOURNEY INT,
     SUM_TOTAL_TOURNEY INT,
     NAME_TOURNEY VARCHAR(50),
     YEAR_TOURNEY INT,
     ID_USER INT,

     CONSTRAINT FOREIGN KEY FK_SCORE_TOURNEY(NAME_TOURNEY, YEAR_TOURNEY) REFERENCES TOURNEY(NAME_TOURNEY, YEAR_TOURNEY),
     CONSTRAINT FOREIGN KEY FK_SCORE_USER(ID_USER) REFERENCES USER_PRODE(ID)

);

CREATE TABLE IF NOT EXISTS SCORE_RESULT(

    ID_SCORE INT,
    ID_RESULT INT,
    CONSTRAINT FOREIGN KEY FK_SCORE_RESULT_INTERMEDIATE(ID_RESULT) REFERENCES RESULT(ID),
    CONSTRAINT FOREIGN KEY FK_RESULT_SCORE_INTERMEDIATE(ID_SCORE) REFERENCES SCORE(ID)
);

CREATE TABLE IF NOT EXISTS FECHA_TOURNEY_RESULT(

   ID_FECHA_TOURNEY INT,
   ID_RESULT INT,
   CONSTRAINT FOREIGN KEY FK_FECHA_TOURNEY_RESULT_INTERMEDIATE(ID_RESULT) REFERENCES RESULT(ID),
   CONSTRAINT FOREIGN KEY FK_RESULT_FECHA_TOURNEY_INTERMEDIATE(ID_FECHA_TOURNEY) REFERENCES FECHA_TOURNEY(ID)
);